#SPDX-License-Identifier: MIT-0
---
# tasks file for swptrshr
- name: check swap is define
  shell: "swapon -s | grep {{ swap_file }}"
  register: swap_active
  ignore_errors: yes

- name: check swap swap_usage
  shell: "free -m | grep -i swap | awk '{print $3}'"
  register: swap_usage

- block:
  - name: turn off swap
    shell: "swapoff {{ swap_file }}"
  
  - name: remove swap from fstab
    mount:
      name: None
      src: "{{ swap_file }}"
      fstype: swap
      opts: swap
      passno: 0
      dump: 0
      state: absent

  - name: delete swap file
    file:
      path: "{{ swap_file }}"
      state: absent
  when: swap_active.rc == 0 and swap_usage.stdout == "0" 