---
- name: "create {{ user }}"
  user:
    name: "{{ user }}"
    password_lock: True
    state: present
    shell: /bin/bash
- name: "add .ssh dir"
  file:
    path: "/home/{{ user }}/.ssh"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0700        
- name: "add ssh key"
  copy:
    src: "/app/infra/roles/usr/files/{{ user }}"
    dest: "/home/{{ user }}/.ssh/authorized_keys"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0600
  when: user_key is defined and item == user
  loop: "{{ user_key.split(',') }}"
- name: "add sudo"
  lineinfile:
    path: "/etc/sudoers.d/{{ user }}"
    create: yes
    state: present
    regexp: "^{{ user }} ALL="
    line: "{{ user }} ALL=(ALL) NOPASSWD: ALL"
    validate: /usr/sbin/visudo -cf %s
  when: sudo_user == 'True'
    
