---
- name: "delete {{ user }}"
  user:
    name: "{{ user }}"
    state: absent

- name: "delete .ssh and sudoers dirs"
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/home/{{ user }}"
    - "/etc/sudoers.d/{{ user }}"
