---
- name: "Create user"
  include_tasks: "create_user.yml"
  args:
    apply:
      become: yes
  loop: "{{ username.split(',') }}"
  loop_control:
    loop_var: user
  when: username is defined and user_state == "present"
- name: "delete user"
  include_tasks: "delete_user.yml"
  args:
    apply:
      become: yes
  loop: "{{ username.split(',') }}"
  loop_control:
    loop_var: user
  when: username is defined and user_state == "absent"
